site_name: Yuri Tabacof – Personal Page
site_author: Yuri Tabacof
site_url: https://yuritaba.github.io/personal_page
repo_url: https://github.com/yuritaba/personal_page
repo_name: yuritaba/personal_page

theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.top
    - navigation.tracking
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # 1) Snippets ANTES do superfences (pra incluir arquivos com --8<--)
  - pymdownx.snippets:
      url_download: true

  # 2) Superfences com custom_fences para Mermaid e markdown-exec
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter

        - name: pyodide          # <<< adicione este
          class: pyodide
          format: !!python/name:markdown_exec.formatter

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - tables

plugins:
  - search
  - minify:
      minify_html: true

  # 3) markdown-exec ligado
  - markdown-exec

# 4) Mermaid JS no front-end
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.js
nav:
  - Home: index.md
  - Exercises:
    - 1. Data: roteiro1/main.md
    - 2. Perceptron: roteiro2/main.md
    - 3. MLP: roteiro3/main.md
    - 4. Metrics: roteiro4/main.md
  - Projeto: projeto/main.md