site_name: Yuri Tabacof – Personal Page
site_author: Yuri Tabacof
site_url: https://yuritaba.github.io/personal_page
repo_url: https://github.com/yuritaba/personal_page
repo_name: yuritaba/personal_page

theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.top
    - navigation.tracking
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - tables

plugins:
  - search

nav:
  - Home: index.md
  - Roteiros:
    - Roteiro 1: roteiro1/main.md
    - Roteiro 2: roteiro2/main.md
    - Roteiro 3: roteiro3/main.md
    - Roteiro 4: roteiro4/main.md
  - Projeto: projeto/main.md